apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: helper
    image: busybox
    command: ['sh', '-c', 'echo Hello from the helper container']
    restartPolicy: Never