apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: data-mount
          mountPath: /data
  volumes:
    - name: data-mount
      emptyDir: {}