apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
spec:
  template:
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
      restartPolicy: Never